import config from 'config';
import express from 'express';
import proxy from 'http-proxy-middleware';

import getUniversalPage from './universal-page';
import helpers from '../../config/helpers';

const IS_PROD = process.env.NODE_ENV === 'prod' || process.env.NODE_ENV === 'production';
// buildHash generated by webpack in separate file (named buildHash.json)
// It is intended to prevent browser scripts caching.
const buildHash =
    IS_PROD
        ? eval('require')('./buildHash.json')
        : null;

const universalPage = getUniversalPage({ buildHash, useStatic: IS_PROD });

const app = express();
const server = config.get('server');

IS_PROD
    ? app.use('/assets', express.static(helpers.root('build', 'assets')))
    : app.use('/assets', proxy({ target: `${server.proxy.host}:${server.proxy.port}` }));

app.get('*', universalPage);

app.listen(server.port, function () {
    console.log(`App listening on port ${server.port}!`);
});
