const TYPES = {
    IZKOMBANK: 'COUNT_TYPE_IZKOMBANK',
    ALFABANK: 'COUNT_TYPE_ALFABANK',
    CASH: 'COUNT_TYPE_CASH',
    MIR: 'COUNT_TYPE_MIR',
    BISTROBANK: 'COUNT_TYPE_BISTROBANK',
    EUR_CASH: 'COUNT_TYPE_EUR_CASH',
    USD_CASH: 'COUNT_TYPE_USD_CASH'
};

export default TYPES;
